server:
  port: 8080
  servlet:
    context-path: /order

spring:
  application:
    name: server-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池
      initial-size: 10
      min-idle: 5
      max-active: 60000
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 3600000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
      table-underline: true
      insert-strategy: not_empty
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'